spring:
  datasource:
    driverClassName: org.h2.Driver #org.postgresql.Driver
    url: jdbc:h2:mem:test; #jdbc:postgresql://localhost:5432/mydb
    username: sa
    password:
    h2:
      console:
        enabled: true
  jpa:
    hibernate.ddl-auto: create #что делать со схемой БД при перезапуске приложения
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect